### ISSUE TITLE
Error in getting claims in iOS app.

### ISSUE THREAD

**Issue by spike-spiegel-21** [0xPolygonID/issuer-node#272]
## Steps that I have followed:

1. Started the sh-id platform. It is running on [http://localhost:3001/]
![Screenshot from 2023-03-29 11-45-17](https://user-images.githubusercontent.com/83648453/228456682-dcbef270-b903-4506-bc29-20bc65ee7b38.png)

2. Using the Postman for API calls. 
![Screenshot from 2023-03-29 11-54-14](https://user-images.githubusercontent.com/83648453/228456961-006047dd-c43e-4a3b-abcc-84f53bb97ef2.png)

3. Identity created.

```jsx
//PrimaryID
did:polygonid:polygon:mumbai:2qPpR9aANjMkvKuCohUfJ7eFxr4T4DpwQfnYGxYgan
```
![Screenshot from 2023-03-29 11-59-22](https://user-images.githubusercontent.com/83648453/228457144-fedc2fcb-465c-4041-b2f4-97a93b5d707a.png)

3. Claim creation.

```jsx
//URL
http://localhost:3001/v1/did:polygonid:polygon:mumbai:2qPpR9aANjMkvKuCohUfJ7eFxr4T4DpwQfnYGxYgan/claims

//Body
{
    "credentialSchema":"https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json/KYCAgeCredential-v100.json",
    "type": "KYCAgeCredential",
    "credentialSubject": {
        "id": "did:polygonid:polygon:mumbai:2qPWTM4gAmVU1zp4XGbmTyLWThecTwiikW69vL9pV8",
        "birthday": 20000424,
        "documentType": 2
    },
    "expiration": 12345
}

//Response
{
    "id": "9689b584-cdfc-11ed-996e-0242ac120005"
}
```

1. Getting the qr code
    

```jsx
{
    "body": {
        "credentials": [
            {
                "description": "https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/kyc-v100.json-ld#KYCAgeCredential",
                "id": "9689b584-cdfc-11ed-996e-0242ac120005"
            }
        ],
        "url": "http://localhost:3001/v1/agent"
    },
    "from": "did:polygonid:polygon:mumbai:2qPpR9aANjMkvKuCohUfJ7eFxr4T4DpwQfnYGxYgan",
    "id": "d4cac217-f681-409c-9944-49865bbef91d",
    "thid": "d4cac217-f681-409c-9944-49865bbef91d",
    "to": "did:polygonid:polygon:mumbai:2qPWTM4gAmVU1zp4XGbmTyLWThecTwiikW69vL9pV8",
    "typ": "application/iden3comm-plain-json",
    "type": "https://iden3-communication.io/credentials/1.0/offer"
}
```
![Screenshot from 2023-03-29 12-37-45](https://user-images.githubusercontent.com/83648453/228457578-1e3dc64f-47fc-4849-b637-f62db6427007.png)

5. Error in getting claim.

I have been using third party app for QR code generation.

But when I scan this with my polygonID app it gets an error.

```jsx
//ID
did:polygonid:polygon:mumbai:2qPWTM4gAmVU1zp4XGbmTyLWThecTwiikW69vL9pV8
```
![WhatsApp Image 2023-03-29 at 12 45 36](https://user-images.githubusercontent.com/83648453/228457661-4f0d9552-6109-4e1a-adf3-dcd77779909b.jpeg)

**Comment by codingwithmanny** [comment]
@spike-spiegel-21 can you return the payload for the claim by running the following:

```bash
curl --location --request GET 'http://localhost:3001/v1/did:polygonid:polygon:mumbai:2qPpR9aANjMkvKuCohUfJ7eFxr4T4DpwQfnYGxYgan/claims/9689b584-cdfc-11ed-996e-0242ac120005' \
--header 'Authorization: Basic YOUR_BASE64_USER_PASS';
```

**Comment by Japskua** [comment]
I am having the same problem. is this related to the fact that everything is running on localhost and the verifier would require a public domain & access?

**Comment by sanketsaagar** [comment]
Hi @Japskua @spike-spiegel-21, Can you guys please fill out the form given below? Thanks

https://docs.google.com/forms/d/e/1FAIpQLSeVZ6y4xJeO-Yz0r2D4u_dWwveHb9cDXIDJWKpP13idhOO8DQ/viewform

**Comment by x1m3** [comment]
Closed due to inactivity. Feel free to reopen the issue or create a new one. Thanks.
