### ISSUE TITLE
Error "cannot process schema" when creating claim

### ISSUE THREAD

**Issue by JaredChilders** [0xPolygonID/issuer-node#343]
Hello, I'm currently trying to create a claim, and I'm running into the following issue. 

**GET Identity**
![Screenshot 2023-04-24 141936](https://user-images.githubusercontent.com/9031951/234082927-9558ff0d-8e97-41cd-bb50-dcb6038ff580.png)

**Create Claim using the identifier**
![Screenshot 2023-04-24 141904](https://user-images.githubusercontent.com/9031951/234082969-3522ec6d-867a-47a7-b279-9e9662aa49b3.png)

Am I doing something wrong? I setup the node as a standalone server as described in the README. Any help would be appreciated thank you.

**Comment by RomanHarazha** [comment]
@JaredChilders did you manage to resolve this issue?
