### ISSUE TITLE
level=ERROR msg="processing the claim against the schema" err="error parsing claim"

### ISSUE THREAD

**Issue by JaredChilders** [0xPolygonID/issuer-node#377]
**Steps to Reproduce Error**

Requirements:
- Release v2.0.0 #373 of `sh-id-platform`
- Intel x86 processor (idk if this makes a difference but I havent tested on M1/M2 processor yet) 
- go1.19.8

I pulled the latest version of the main branch and followed the instructions to set up the Issuer node locally. I did the following steps when setting up the Issuer node:
1. Create Docker Configuration Files (.env-api, .env-issuer, .env-ui)
2. Configured the `.env-issuer` with ISSUER_ETHEREUM_URL
3. I removed the docker images, so that docker would need to re pull them and download then again
``` 
docker rmi postgres:14-alpine
docker rmi vault:latest
docker rmi redis:6-alpine
```
4. Ran `make up`
5. Imported Wallet Private Key To Vault with `make private_key=<YOUR_WALLET_PRIVATE_KEY> add-private-key;`
6. Added Vault To Configuration File with `make add-vault-token;`
7. Created Issuer DID with `make generate-issuer-did;`
8. Started Issuer API with `make run;`
9. Set the Authentication username and password in the Issuer UI, by what is defined under the environment variables in the `.env-issuer` config file

Then using the `identifier` that is generated in **step 7** (`did:polygonid:polygon:mumbai:2qHayFwfcKLQjbH6HFBNqAebYHXXcB2Q7ygP6cKGSf`). I used the identifier to complete the request to Create a Claim (using it as a input in the parameter and in the POST body. 

**Default example POST body with the generated Issuer DID:**
```
{
  "credentialSchema": "https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json/KYCAgeCredential-v3.json",
  "type": "KYCAgeCredential",
  "credentialSubject": {
    "id": "did:polygonid:polygon:mumbai:2qHayFwfcKLQjbH6HFBNqAebYHXXcB2Q7ygP6cKGSf",
    "birthday": 19960424,
    "documentType": 2
  },
  "expiration": 1903357766
} 
```
**Photo of the request in the Issuer UI**
![after](https://user-images.githubusercontent.com/9031951/235959663-efcbda4a-ab6f-41d9-bc52-40ef19ed1bc6.png)

Everything looks good, but when I make the request to Create a Claim I receive the following error:

**Response Error 400**
`level=ERROR msg="processing the claim against the schema" err="error parsing claim"`

**Photo of the error in the terminal**
![Screenshot 2023-05-02 133535](https://user-images.githubusercontent.com/9031951/235960128-28c1ffa1-c497-4ba9-9c7b-f87c4a7eeba3.png)

I submitted a ticket to PolygonID support and they said that everything should be working just fine. The body I used to make the request should not be throwing an error. Am I missing a something?

**Comment by preet-jain** [comment]
Here your issuer id and user id is same that shouldn't be the case
