### ISSUE TITLE
Cannot verify claims through verifier demo

### ISSUE THREAD

**Issue by MattBash17** [0xPolygonID/issuer-node#383]
For some reason the verifier demo (the one in the official documentation) does not seem to work with claims issued with a custom schema. Also tried the same schema with the issuer-demo platform from the docs, and the verifier still cannot verify the claim.
Not sure if this is a known bug or not.

**Comment by sanketsaagar** [comment]
Hi @MattBash17 , Can you please share the link of the verifier which you are using and also the screenshot of the error?

**Comment by x1m3** [comment]
Closed due to inactivity. Feel free to reopen the issue or create a new one. Thanks.
