### ISSUE TITLE
Standalone build error with make db/migrate

### ISSUE THREAD

**Issue by Japskua** [0xPolygonID/issuer-node#408]
Hi!
When I am running the command "db/migrate" as instructed [by the readme at step 3](https://github.com/0xPolygonID/issuer-node#standalone-mode-setup), I get the following error:

> make db/migrate
install github.com/pressly/goose/v3
install: missing destination file operand after 'github.com/pressly/goose/v3'

**Comment by sanketsaagar** [comment]
Hi @Japskua , Can you tell me the version of go ? As you are using the standalone mode you must have go installed, as suggested 1.20 but 1.19 would work as well.

**Comment by Japskua** [comment]
Hi! Here's the details:
go version go1.20.4 linux/amd64
Current main branch for today: 09468f5d344d7a0226633fce4b62bc5cd489f3ba

**Comment by Japskua** [comment]
And I have to admit, that after rebooting the entire Ubuntu server, the migrate command started working...

**Comment by sanketsaagar** [comment]
Thanks @Japskua
