### ISSUE TITLE
Standalone build error

### ISSUE THREAD

**Issue by NerdyLucifer** [0xPolygonID/issuer-node#409]
After running the command "make db/migrate".
I am getting the following log:
<img width="1366" alt="Screenshot 2023-05-15 at 20 28 57" src="https://github.com/0xPolygonID/issuer-node/assets/85362194/ab06eb7d-8b56-4511-a58c-1ccc62de8f22">

**Comment by sanketsaagar** [comment]
Hi @NerdyLucifer , it seems Postgres container is not running, Could you please tell me the result of running 
`docker ps` and `docker ps -a` in the terminal?

**Comment by NerdyLucifer** [comment]
Thanks! @sanketsaagar, I successfully set up the local environment using docker. So the stopped containers, as you can see in the screenshot, were used for it. I can't see any container running when I try to perform a standalone setup.
<img width="1298" alt="Screenshot 2023-05-16 at 19 49 28" src="https://github.com/0xPolygonID/issuer-node/assets/85362194/4c743644-c22b-4fa4-8116-6ffcdee0a92e">

**Comment by sanketsaagar** [comment]
@NerdyLucifer Did you try the command? Also let us know if your issue is resolved or not.

**Comment by aaishikasb** [comment]
Hey @sanketsaagar, I am facing similar issues while trying to self-host the issuer node. Can you please take a look at my result of running `docker logs issuer-postgres-1`?

<img width="1728" alt="Screenshot 2023-05-30 at 7 01 38 PM" src="https://github.com/0xPolygonID/issuer-node/assets/52964353/8ba5c21e-41f6-4b1e-a1bc-4d25182d3889">

**Comment by aaishikasb** [comment]
Thanks for the speedy response!
Here, what next?

<img width="1297" alt="Screenshot 2023-05-30 at 7 20 50 PM" src="https://github.com/0xPolygonID/issuer-node/assets/52964353/fc9ba578-66a8-4947-9712-1fc6e159469d">

**Comment by sanketsaagar** [comment]
Can you try 

1. sudo su
2. make up

**Comment by aaishikasb** [comment]
Done, still not able to connect. What do I do next?

<img width="1537" alt="Screenshot 2023-05-30 at 7 50 37 PM" src="https://github.com/0xPolygonID/issuer-node/assets/52964353/db3bf704-77e5-48c5-831b-78a996bb7962">

**Comment by aaishikasb** [comment]
Here you go:

<img width="1728" alt="Screenshot 2023-05-30 at 8 06 19 PM" src="https://github.com/0xPolygonID/issuer-node/assets/52964353/db4c775b-b21a-4e32-a374-a75aa959884c">

**Comment by sanketsaagar** [comment]
@aaishikasb You can stop and remove the containers (issuer node containers) and start them again.

**Comment by aaishikasb** [comment]
Hey @sanketsaagar, is there a possibility for us to connect outside of GitHub to figure out the issues 1:1?

**Comment by sanketsaagar** [comment]
Hi @aaishikasb , It would be better for us to solve the issue here. At this point in time, it's not possible for 1:1. Did you tried to remove the containers and start them again?

**Comment by aaishikasb** [comment]
No luck so far, tried starting from scratch and I get stuck at the same point every single time.

**Comment by sanketsaagar** [comment]
So this env var `ISSUER_ETHEREUM_UR`L has this value: `<Ethereum URL of the Issuer>` and that is not correct. That en var must have the RPC URL.

**Comment by nagarjun-repala** [comment]
"make build" is not generating the binaries as per the documentation and I was able to execute "make db/migrate" after that
"./bin/platform", "./bin/pending_publisher" are not part of of bin directory to start the issuer.
![Screenshot from 2023-06-01 13-47-51](https://github.com/0xPolygonID/issuer-node/assets/61962408/71747f79-af8e-4669-8c19-bf3d1a286a56)

Logs after "make db/migrate"
```
2023/06/01 14:06:03 INFO ISSUER_API_UI_SERVER_PORT value is missing
2023/06/01 14:06:03 INFO ISSUER_API_UI_SERVER_URL value is missing
2023/06/01 14:06:03 INFO ISSUER_API_UI_AUTH_USER value is missing
2023/06/01 14:06:03 INFO ISSUER_API_UI_AUTH_PASSWORD value is missing
2023/06/01 14:06:03 INFO ISSUER_API_UI_ISSUER_NAME value is missing
2023/06/01 14:06:03 INFO ISSUER_API_UI_ISSUER_DID value is missing
2023/06/01 14:06:03 INFO ISSUER_API_UI_SCHEMA_CACHE is missing and the server set up it as false
2023/06/01 14:06:03 INFO ISSUER_API_IDENTITY_METHOD value is missing and the server set up it as polygonid
2023/06/01 14:06:03 INFO ISSUER_API_IDENTITY_BLOCKCHAIN value is missing and the server set up it as polygon
2023/06/01 14:06:03 INFO ISSUER_API_IDENTITY_NETWORK value is missing and the server set up it as mumbai
time=2023-06-01T14:06:03.559+05:30 level=DEBUG msg=database url="postgres://polygonid:polygonid@localhost:5432/platformid?sslmode=disable"
2023/06/01 14:06:03 goose: no migrations to run. current version: 202304121507181
time=2023-06-01T14:06:03.572+05:30 level=INFO msg="migration done!"
```

**Comment by nagarjun-repala** [comment]
> After running the command "make db/migrate". I am getting the following log: <img alt="Screenshot 2023-05-15 at 20 28 57" width="1366" src="https://user-images.githubusercontent.com/85362194/238389015-ab06eb7d-8b56-4511-a58c-1ccc62de8f22.png">

Change it to localhost:5432 instead of postgres:5432 because the migrate command is running on the host machine and the postgres:5432 dns is resolved in the docker network.

**Comment by martinsaporiti** [comment]
`make build-local` will build and place binaries in `sh-id-platform/bin/` folder.
regarding postgres, redis and vault, you should put the correct address. If you are running migration or the issuer node outside docker, then you must put localhost:xxx. Before that be dure you already run `make up`.

**Comment by markoftw** [comment]
> "make build" is not generating the binaries as per the documentation and I was able to execute "make db/migrate" after that "./bin/platform", "./bin/pending_publisher" are not part of of bin directory to start the issuer. ![Screenshot from 2023-06-01 13-47-51](https://user-images.githubusercontent.com/61962408/242540355-71747f79-af8e-4669-8c19-bf3d1a286a56.png)
> 
> Logs after "make db/migrate"
> 
> ```
> 2023/06/01 14:06:03 INFO ISSUER_API_UI_SERVER_PORT value is missing
> 2023/06/01 14:06:03 INFO ISSUER_API_UI_SERVER_URL value is missing
> 2023/06/01 14:06:03 INFO ISSUER_API_UI_AUTH_USER value is missing
> 2023/06/01 14:06:03 INFO ISSUER_API_UI_AUTH_PASSWORD value is missing
> 2023/06/01 14:06:03 INFO ISSUER_API_UI_ISSUER_NAME value is missing
> 2023/06/01 14:06:03 INFO ISSUER_API_UI_ISSUER_DID value is missing
> 2023/06/01 14:06:03 INFO ISSUER_API_UI_SCHEMA_CACHE is missing and the server set up it as false
> 2023/06/01 14:06:03 INFO ISSUER_API_IDENTITY_METHOD value is missing and the server set up it as polygonid
> 2023/06/01 14:06:03 INFO ISSUER_API_IDENTITY_BLOCKCHAIN value is missing and the server set up it as polygon
> 2023/06/01 14:06:03 INFO ISSUER_API_IDENTITY_NETWORK value is missing and the server set up it as mumbai
> time=2023-06-01T14:06:03.559+05:30 level=DEBUG msg=database url="postgres://polygonid:polygonid@localhost:5432/platformid?sslmode=disable"
> 2023/06/01 14:06:03 goose: no migrations to run. current version: 202304121507181
> time=2023-06-01T14:06:03.572+05:30 level=INFO msg="migration done!"
> ```
> 
> Instead of "make build" use "make build-local" worked for me but the application is not able to read .env variables

Same here, unable to read any of the .env files. Also noticed it used some path to find a toml file that doesn't exist "INFO missing toml config file. Fallback to env vars err="Config File \"config\" Not Found in \"[/home/marko/issuer-node **/home/runner/work/sh-id-platform/sh-id-platform**]\""

Meanwhile, the Docker setup works fine.

![image](https://github.com/0xPolygonID/issuer-node/assets/1616694/6d48a14f-ea3c-48a4-90c3-44790719c919)

**Comment by preet-jain** [comment]
I am also facing the same issue

**Comment by sanketsaagar** [comment]
Hi @preet-jain , Hope we are having better communication over Discord. So I request you to stay in one place for us to have your problem solved.

**Comment by x1m3** [comment]
Closed due to inactivity. Feel free to reopen the issue or create a new one. Thanks.
