### ISSUE TITLE
Receiving "Cannot load schema" as response on sending Create credentials request

### ISSUE THREAD

**Issue by NerdyLucifer** [0xPolygonID/issuer-node#412]
I received the following response on sending a 'Create Credentials' request via API UI.
I tried sending the request using Postman but still got the same response.
<img width="1062" alt="Screenshot 2023-05-18 at 17 06 03" src="https://github.com/0xPolygonID/issuer-node/assets/85362194/4c560f22-f54f-4045-82b5-9344a055ec30">

**Comment by drraghavendra** [comment]
The error message "Cannot load schema" typically indicates that there is an issue with loading the schema for the credential you are trying to create using the Polygon web3 library. This error can occur if the schema is not properly defined or if there is an issue with the schema file itself.

To resolve this issue, you can check the following:

Verify the schema: Make sure that the schema you are trying to use is correctly defined and accessible. Ensure that the schema file exists and is located at the specified path or URL.

Check the schema file format: Ensure that the schema file is in the correct format, such as JSON or YAML, depending on the requirements of the Polygon web3 library.

Validate the schema: Use a JSON or YAML schema validator to ensure that the schema file is valid and conforms to the expected structure. This step can help identify any syntax errors or inconsistencies in the schema definition.

Confirm the schema loading process: Double-check the code or configuration where the schema is being loaded. Ensure that the correct path or URL is specified and that the loading process is functioning as intended.

Verify network connectivity: If the schema is loaded from a remote URL, ensure that your application has network connectivity and can access the specified URL. Check for any firewall restrictions or network issues that may prevent the schema from being loaded.

If you have reviewed these steps and the issue persists, it may be helpful to consult the documentation or seek assistance from the Polygon web3 library's support channels for further guidance on troubleshooting this specific error.

**Comment by x1m3** [comment]
Closed due to inactivity. Feel free to reopen the issue or create a new one. Thanks.
