### ISSUE TITLE
Why should an issuer generate auth claim when first create the issuer identity? 

### ISSUE THREAD

**Issue by hero5512** [0xPolygonID/issuer-node#414]
thx

**Comment by Groovytent** [comment]
Auth BJJ credential includes a  baby jub jub public key. The corresponding private key is used to transit the issuer state.
without it, it’s not possible.
Also, the issuer id is derived from genesis state.  And genesis state must include smth to differentiate the users. It’s auth credential.

**Comment by x1m3** [comment]
Closed due to inactivity. Feel free to reopen the issue or create a new one. Thanks.
