### ISSUE TITLE
Fix the makefile, docker-compose

### ISSUE THREAD

**Issue by Fbartoli** [0xPolygonID/issuer-node#419]
DOCKER_COMPOSE_CMD := docker compose -p issuer -f $(DOCKER_COMPOSE_FILE)
DOCKER_COMPOSE_INFRA_CMD := docker compose -p issuer -f $(DOCKER_COMPOSE_FILE_INFRA)

- dashes are missing between docker and compose 

DOCKER_COMPOSE_CMD := docker-compose -p issuer -f $(DOCKER_COMPOSE_FILE)
DOCKER_COMPOSE_INFRA_CMD := docker-compose -p issuer -f $(DOCKER_COMPOSE_FILE_INFRA)

**Comment by sanketsaagar** [comment]
Hi @Fbartoli , That is because you are running an old docker-compose version. The latest version runs like this: `docker-compose xxxx`

**Comment by sanketsaagar** [comment]
Hi @Fbartoli , Didn't hear back from you for a few days, Are you still facing issues?
