### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by andrewzhang97** [0xPolygonID/issuer-node#421]
![image](https://github.com/0xPolygonID/issuer-node/assets/25349939/e853fdd5-339c-4e57-979f-da6ced61b1b9)
![image](https://github.com/0xPolygonID/issuer-node/assets/25349939/131b33f9-05f3-4bf8-982c-9558b188fd84)
why this cmd cannot successfully run

**Comment by andrewzhang97** [comment]
![image](https://github.com/0xPolygonID/issuer-node/assets/25349939/ad5fde17-5971-44f2-8ff3-cbb112583493)
and this problem when I create claim.

**Comment by sanketsaagar** [comment]
Hi @andrewzhang97, please share issuer-API container logs.

**Comment by andrewzhang97** [comment]
> Hi @andrewzhang97, please share issuer-API container logs.

![image](https://github.com/0xPolygonID/issuer-node/assets/25349939/f1aa852e-b70b-42e7-ba10-0b053acf644f)
here it is for the second problem.

**Comment by sanketsaagar** [comment]
Hi @andrewzhang97 , we tried the latest version of the issuer node with this payload and worked perfectly, let’s make sure that you have the latest version. 

```
{    "credentialSchema":"https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json/KYCAgeCredential-v3.json",
    "type": "KYCAgeCredential",
    "credentialSubject": {
        "id": "did:polygonid:polygon:mumbai:2qMZrfBsXuGFTwSqkqYki78zF3pe1vtXoqH4yRLsfs",
        "birthday": 19960424,
        "documentType": 2
    },
    "expiration": 1903357766
}
```

**Comment by andrewzhang97** [comment]
> Hi @andrewzhang97 , we tried the latest version of the issuer node with this payload and worked perfectly, let’s make sure that you have the latest version.
> 
> ```
> {    "credentialSchema":"https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json/KYCAgeCredential-v3.json",
>     "type": "KYCAgeCredential",
>     "credentialSubject": {
>         "id": "did:polygonid:polygon:mumbai:2qMZrfBsXuGFTwSqkqYki78zF3pe1vtXoqH4yRLsfs",
>         "birthday": 19960424,
>         "documentType": 2
>     },
>     "expiration": 1903357766
> }
> ```

The problem is solved. I restarted and problem was gone. Thanks for your help. Appreciate.

**Comment by sanketsaagar** [comment]
Hi @andrewzhang97 , Since your problem is solved can you please close this issue?
