### ISSUE TITLE
vault error

### ISSUE THREAD

**Issue by adhvaitaganesh** [0xPolygonID/issuer-node#447]
Error while executing make up; 

console log: 
docker compose -p issuer -f /Users/ganeshgopalkrishnahegde/IDissuer/issuer-node/infrastructure/local/docker-compose-infra.yml up -d redis postgres vault
[+] Running 1/1
 ✘ vault Error                                                                                                                                                                                                   1.7s 
Error response from daemon: manifest for vault:latest not found: manifest unknown: manifest unknown
make: *** [up] Error 18

**Comment by markoftw** [comment]
It seems to be fixed on the "develop" branch. If you want to use the main one, change in the docker-compose-infra.yml to 1.13.2.

**Comment by x1m3** [comment]
Closed due to inactivity. Feel free to reopen the issue or create a new one. Thanks.
