### ISSUE TITLE
issuer-initializer doesn't allow empty NoChain nor NoNetwork

### ISSUE THREAD

**Issue by tzx** [0xPolygonID/issuer-node#465]
Relevant file: https://github.com/0xPolygonID/issuer-node/blob/f9baf7285d7ddb1e953b9820ca62c20f2bb55049/internal/config/config.go#L552-L560

Both NoChain and NoNetwork are configured as empty strings, but the config file overrides them as they are seen as empty. The issue initializer reads from the config file, so it causes a `wrong DID Metadata` error.

**Comment by x1m3** [comment]
Closed due to inactivity. Feel free to reopen the issue or create a new one. Thanks.
