### ISSUE TITLE
Error at issuer node ui

### ISSUE THREAD

**Issue by raghav-goyal-coindcx** [0xPolygonID/issuer-node#466]
![Screenshot 2023-07-17 at 1 03 47 PM](https://github.com/0xPolygonID/issuer-node/assets/126654416/96ce8d17-a6a6-4269-9980-877333abebe3)

**Comment by Groovytent** [comment]
you have to give a value to that variable in the .env-ui file.
example:
VITE_IPFS_GATEWAY_URL=https://ipfs.io/

**Comment by raghav-goyal-coindcx** [comment]
It worked
but now it shows `network error`
![Screenshot 2023-07-17 at 4 27 07 PM](https://github.com/0xPolygonID/issuer-node/assets/126654416/7f43e977-fa3a-472a-876e-1a39dc85c21e)
have tried `make down` and starting up the containers again, but it didn't work

**Comment by Groovytent** [comment]
what is the value of this env var ISSUER_API_UI_SERVER_URL ?

**Comment by raghav-goyal-coindcx** [comment]
Have replaced it with an ngrok forwarding URL
`https://xxxx-xxx-xx-xxx-xx.ngrok-free.app`

**Comment by Groovytent** [comment]
well, we need more information to figure out what the problem is. For instance, what is saying the browser console or the network tab on it
and what is the response when visiting the ngrok URL in the browser

**Comment by raghav-goyal-coindcx** [comment]
Have fixed this one. I am using a VPN that blocked making call to ngrok forwarding url.

**Comment by raghav-goyal-coindcx** [comment]
I also wanted to know in we can update claims issued via issuer node? if yes how it can be done for both Sig and MT based claims?

**Comment by Groovytent** [comment]
with the current version of the issuer node, updating claims is not possible, issuer can issue and revoke credentials but not update (as for now)

**Comment by raghav-goyal-coindcx** [comment]
Alright! that was really helpful.
Closing this issue.
