### ISSUE TITLE
Make Build-local fail in Standalone

### ISSUE THREAD

**Issue by preet-jain** [0xPolygonID/issuer-node#471]
`package github.com/polygonid/sh-id-platform/cmd/issuer_initializer
        imports github.com/polygonid/sh-id-platform/internal/core/services
        imports github.com/iden3/go-rapidsnark/prover: build constraints exclude all Go files in /home/ubuntu/go/pkg/mod/github.com/iden3/go-rapidsnark/prover@v0.0.10
make: *** [Makefile:24: build-local] Error 1` 

Got this error after running the command `make build-local`

**Comment by preet-jain** [comment]
That didn't work still same error

**Comment by mcwnuq** [comment]
I have the same problem. After running `go clean -modcache` and `make build-local` i got the same error.

**Comment by krzysiekw-78** [comment]
Probably solution is decribed here: https://github.com/iden3/rapidsnark
You have to install:
`sudo apt-get install build-essential cmake libgmp-dev libsodium-dev nasm`

**Comment by mcwnuq** [comment]
Thank you very much, it worked.

**Comment by x1m3** [comment]
Closed due to inactivity. Feel free to reopen the issue or create a new one. Thanks.
