### ISSUE TITLE
Build Failed Due to the unknown dependecy revision (lestrrat-go/jwx/v2)

### ISSUE THREAD

**Issue by gamer31dev** [0xPolygonID/issuer-node#519]
I'm trying to build PolygonID in Standalone mode in Amazon Linux.
Im using **go version go1.20.10 linux/amd64**

Error Im getting is following:
`../../go/pkg/mod/github.com/iden3/iden3comm@v1.0.1-0.20230609100900-191d60f4f566/packers/providers/bjj/bjj.go:11:2: github.com/lestrrat-go/jwx/v2@v2.0.9-0.20230429214153-5090ec1bd2cd: invalid version: unknown revision 5090ec1bd2cd
../../go/pkg/mod/github.com/iden3/iden3comm@v1.0.1-0.20230609100900-191d60f4f566/packers/providers/bjj/utils.go:11:2: github.com/lestrrat-go/jwx/v2@v2.0.9-0.20230429214153-5090ec1bd2cd: invalid version: unknown revision 5090ec1bd2cd
../../go/pkg/mod/github.com/iden3/iden3comm@v1.0.1-0.20230609100900-191d60f4f566/packers/jws.go:18:2: github.com/lestrrat-go/jwx/v2@v2.0.9-0.20230429214153-5090ec1bd2cd: invalid version: unknown revision 5090ec1bd2cd
make: *** [Makefile:24: build-local] Error 1`

I've tried **go clean -modcache** but it doesn't help.
I think the owner of the **lestrrat-go/jwx/v2** merged branches or something like that.
I think that the URL or version that is in go.mod doesn't exist anymore.

**Comment by x1m3** [comment]
@gamer31dev we've tested it with an intel arch linux box running `go1.20.3 linux/amd64` and a mac with `go1.20.4 darwin/arm64` and it compiles downloading the module.

What is the output for `go get [github.com/lestrrat-go/jwx/v2@v2.0.9-0.20230429214153-5090ec1bd2cd](http://github.com/lestrrat-go/jwx/v2@v2.0.9-0.20230429214153-5090ec1bd2cd)` ? In my case it download the file without errors.

We are about to do a new release during this week. Pull request is here https://github.com/0xPolygonID/issuer-node/pull/516

In that new release, the version has changed to `github.com/lestrrat-go/jwx/v2 v2.0.16` so maybe this helps in your case.

**Comment by ilya-korotya** [comment]
I created an Amazon Linux instance in AWS with the same golang version (go version go1.20.10 linux/amd64). I was able to spin up the issuer-node without any problems.

**Comment by gamer31dev** [comment]
Thanks for the replies, I will try to download the new version you mentioned and try to do the same. Its very strange that you are not getting those errors :(

Im getting this error : 
`
../../go/pkg/mod/github.com/iden3/iden3comm@v1.0.1-0.20230609100900-191d60f4f566/packers/providers/bjj/bjj.go:11:2: github.com/lestrrat-go/jwx/v2@v2.0.9-0.20230429214153-5090ec1bd2cd: invalid version: unknown revision 5090ec1bd2cd
../../go/pkg/mod/github.com/iden3/iden3comm@v1.0.1-0.20230609100900-191d60f4f566/packers/providers/bjj/utils.go:11:2: github.com/lestrrat-go/jwx/v2@v2.0.9-0.20230429214153-5090ec1bd2cd: invalid version: unknown revision 5090ec1bd2cd
../../go/pkg/mod/github.com/iden3/iden3comm@v1.0.1-0.20230609100900-191d60f4f566/packers/jws.go:18:2: github.com/lestrrat-go/jwx/v2@v2.0.9-0.20230429214153-5090ec1bd2cd: invalid version: unknown revision 5090ec1bd2cd
`

**Comment by x1m3** [comment]
There is a new release. https://github.com/0xPolygonID/issuer-node/releases/tag/v2.3.0

**Comment by gamer31dev** [comment]
I've used the new release and issue is not present anymore.
Thanks for support!
