### ISSUE TITLE
ISSUER UI for docker setup doesn't work.

### ISSUE THREAD

**Issue by skywormfol** [0xPolygonID/issuer-node#520]
https://devs.polygonid.com/docs/issuer/setup-issuer-ui/#optional-using-the-ui

while setting up the ISSUER UI page according to above guidelines, an error is shown for "localhost:8088", any browser or "http://user-api:password-api@localhost:8088/." in NOTE doesn't solve it. What's the possible reason? Thanks.

"Something went wrong
An error occurred while reading the environment variables:
Invalid url at VITE_IPFS_GATEWAY_URL
Please provide valid environment variables."

<img width="536" alt="image" src="https://github.com/0xPolygonID/issuer-node/assets/28553281/218aebd0-7396-46c2-80a8-e1d86366c1ce">

**Comment by amonsosanz** [comment]
Hi there! You're missing a value for the env var `ISSUER_UI_IPFS_GATEWAY_URL` in your `.env-ui` file. You can use `https://ipfs.io` or any other gateway.

This missing value has been already added in the `develop` branch as you can see [here](https://github.com/0xPolygonID/issuer-node/blob/09f28bc6ec5b85471b2babc1b750ad547708aba2/.env-ui.sample#L6). It will be in `main` soon.

**Comment by skywormfol** [comment]
> Hi there! You're missing a value for the env var `ISSUER_UI_IPFS_GATEWAY_URL` in your `.env-ui` file. You can use `https://ipfs.io` or any other gateway.
> 
> This missing value has been already added in the `develop` branch as you can see [here](https://github.com/0xPolygonID/issuer-node/blob/09f28bc6ec5b85471b2babc1b750ad547708aba2/.env-ui.sample#L6). It will be in `main` soon.

Thank you for your quick response, it solved my problem, but I got a new one when I launched the webpage, it shows as follows, do you know the possible reason? I cannot import schema as it reminds me "network error"...

<img width="1870" alt="image" src="https://github.com/0xPolygonID/issuer-node/assets/28553281/eb41e8bf-e98d-42fc-8125-8ca99baf6d8f">


Thanks a lot!

**Comment by bfondevila** [comment]
> > Hi there! You're missing a value for the env var `ISSUER_UI_IPFS_GATEWAY_URL` in your `.env-ui` file. You can use `https://ipfs.io` or any other gateway.
> > This missing value has been already added in the `develop` branch as you can see [here](https://github.com/0xPolygonID/issuer-node/blob/09f28bc6ec5b85471b2babc1b750ad547708aba2/.env-ui.sample#L6). It will be in `main` soon.
> 
> Thank you for your quick response, it solved my problem, but I got a new one when I launched the webpage, it shows as follows, do you know the possible reason? I cannot import schema as it reminds me "network error"...
> 
> <img alt="image" width="1870" src="https://user-images.githubusercontent.com/28553281/281761149-eb41e8bf-e98d-42fc-8125-8ca99baf6d8f.png">
> Thanks a lot!

Hey @skywormfol. Have you checked what error you get in the console logs?
This looks like a communication error with the api-ui, but knowing if it's a CORS error, or 403 Forbidden, etc. would help.

**Comment by amonsosanz** [comment]
Can you please open the browser dev tools, go to Network, and show some details about the error on the request/response to the endpoint `/schemas`?

**Comment by Raj6939** [comment]
I am missing anything? this is the response in terminal when I run the command ```make run-ui```.
![Screenshot from 2023-11-13 18-51-48](https://github.com/0xPolygonID/issuer-node/assets/67961128/f6fd2038-86f7-4a86-ba04-21ea75d94db9)

**Comment by amonsosanz** [comment]
This looks ok! Can you provide a video or screenshot of what you see in the Headers tab?

https://github.com/0xPolygonID/issuer-node/assets/15896177/dbb5b648-8845-4ad0-90a7-5141a4014f95

**Comment by amonsosanz** [comment]
Are you guys using ngrok by any chance?

**Comment by Raj6939** [comment]
@amonsosanz  Yes I am using ngrok. 

[Screencast from 13-11-23 07:15:13 PM IST.webm](https://github.com/0xPolygonID/issuer-node/assets/67961128/9c4f8f82-cb9d-4305-b62f-6522ac5d42ea)

**Comment by amonsosanz** [comment]
Can you please give [LocalTunnel](https://theboroer.github.io/localtunnel-www) a try? We've had issues in the past with ngrok removing the header `Access-Control-Allow-Origin`, which produces this CORS issue.

**Comment by Raj6939** [comment]
Do I need to mention the url I got from localTunnel in ```env-api``` as ISSUER_API_UI_SERVER_URL= local tunnel url? or its value would be ```http://localhost:3002```

**Comment by amonsosanz** [comment]
Exactly, set up the public URL you get from LocalTunnel in `ISSUER_API_UI_SERVER_URL` (as I assume you were doing with the URL you got from ngrok) and restart the server.

**Comment by Raj6939** [comment]
I am getting the same error even after setting up a new LocalTunnel URL in env and restarting the server

**Comment by Raj6939** [comment]
How much images should run once we enter command as ```make up```?
I hope my integration is right. correct me if i am doing wrong
![image](https://github.com/0xPolygonID/issuer-node/assets/67961128/91ca2c4d-f27f-4a03-a0e6-70b786a11869)

**Comment by amonsosanz** [comment]
Yep, this looks correct, but keep in mind that this command shows the containers that have been booted and some could go down later. To see what you currently have running use `docker ps`.

**Comment by Raj6939** [comment]
Yes I have tried ps command
is it correct or I am running less images than expected?
![image](https://github.com/0xPolygonID/issuer-node/assets/67961128/1830ce33-8d28-4cec-8754-25994dc0ac09)

**Comment by Raj6939** [comment]
@amonsosanz I am trying to use Issuer-UI-API as mentioned in the documentation but not able to navigate to ```http://localhost:3002``` as its not showing anything in a browser

**Comment by amonsosanz** [comment]
> its not showing anything in a browser

Yep, this is because your API service is down, along with redis. You should have these running:

```bash
$ docker ps 
CONTAINER ID   IMAGE                COMMAND                  CREATED          STATUS                    PORTS                    NAMES
755ce726cf0d   issuer-ui            "/bin/sh /app/script…"   34 minutes ago   Up 34 minutes             0.0.0.0:8088->80/tcp     issuer-ui-1
7db68e83a116   issuer-api           "sh -c 'sleep 4s && …"   52 minutes ago   Up 52 minutes             0.0.0.0:3001->3001/tcp   issuer-api-1
505a71889f5c   postgres:14-alpine   "docker-entrypoint.s…"   52 minutes ago   Up 52 minutes (healthy)   0.0.0.0:5432->5432/tcp   issuer-postgres-1
13f35a7df1b5   redis:6-alpine       "docker-entrypoint.s…"   52 minutes ago   Up 52 minutes (healthy)   0.0.0.0:6379->6379/tcp   issuer-redis-1
27a16c5e15ee   vault:1.13.2         "docker-entrypoint.s…"   52 minutes ago   Up 52 minutes             0.0.0.0:8200->8200/tcp   issuer-vault-1
```

I'd execute `make down` to stop everything.

Then `make up` should boot 3 containers.

```bash
$ make up
docker compose -p issuer -f /polygonid/issuer-node/infrastructure/local/docker-compose-infra.yml up -d redis postgres vault
[+] Building 0.0s (0/0)                                                                                                                                                                                                                            
[+] Running 4/4
 ✔ Network issuer-network       Created                                                                                                                                                                                                       0.0s 
 ✔ Container issuer-redis-1     Started                                                                                                                                                                                                       0.4s 
 ✔ Container issuer-vault-1     Started                                                                                                                                                                                                       0.4s 
 ✔ Container issuer-postgres-1  Started                        
```

And doing `docker ps` later should show them running.

```bash
$ docker ps
CONTAINER ID   IMAGE                COMMAND                  CREATED         STATUS                            PORTS                    NAMES
a1fa0725ef7a   postgres:14-alpine   "docker-entrypoint.s…"   5 seconds ago   Up 4 seconds (health: starting)   0.0.0.0:5432->5432/tcp   issuer-postgres-1
f01ea5f8991f   redis:6-alpine       "docker-entrypoint.s…"   5 seconds ago   Up 4 seconds (health: starting)   0.0.0.0:6379->6379/tcp   issuer-redis-1
d9566fb4dfcc   vault:1.13.2         "docker-entrypoint.s…"   5 seconds ago   Up 4 seconds                      0.0.0.0:8200->8200/tcp   issuer-vault-1
```

Then for Apple M1/M2 run `make run-arm`. Otherwise, run `make run` to start the issuer API.

**Comment by Raj6939** [comment]
Thank you for the detail answer @amonsosanz . Sometimes redis goes down and sometimes API. How to get all live running?

**Comment by Raj6939** [comment]
@amonsosanz When I run ```make run-ui``` the issuer-redis-1 comes as ```Created``` instead of ```Started```.
can you tell Why its like that?
```
sudo make up
docker compose -p issuer -f /home/raj-patil/code/issuer-node/infrastructure/local/docker-compose-infra.yml up -d redis postgres vault
[+] Running 4/4
 ✔ Network issuer-network       Created                                                                                                         0.1s 
 ✔ Container issuer-redis-1     Created                                                                                                         0.2s 
 ✔ Container issuer-postgres-1  Started                                                                                                         0.2s 
 ✔ Container issuer-vault-1     Started                                                                                                         0.2s 
```

**Comment by amonsosanz** [comment]
Nope. Is it running later when you run a `docker ps`?

By the way, I've just realized that you (and me 😅) are missing another service: `issuer-api-ui-1`.

This is the actual API used by the UI. It's been a while since I ran this project locally, let me investigate this and come back to you ASAP.

**Comment by Raj6939** [comment]
No After run ```docker ps```these are the running images I get. 

![image](https://github.com/0xPolygonID/issuer-node/assets/67961128/75cb6b2e-847c-432a-942d-77ec1c7a488e)

**Comment by amonsosanz** [comment]
Can paste the output of `docker start issuer-redis-1 && docker logs issuer-redis-1`?

**Comment by Raj6939** [comment]
@amonsosanz Sure, I am getting this error after running above command

```

sudo docker start issuer-redis-1 && docker logs issuer-redis-1
Error response from daemon: driver failed programming external connectivity on endpoint issuer-redis-    (b78bcc1a7376f38867160be9086160f639d56b55b178a9ed320c88861825974a): Error starting userland proxy: listen tcp4 0.0.0.0:6379: bind: address already in use
Error: failed to start containers: issuer-redis-1

```

**Comment by amonsosanz** [comment]
mmm... apparently the port is in use. Do you have any other service on this port? Without this port redis can't start.

I'd stop all the containers `docker stop $(docker ps -a -q)` and try to guess who's using the port `lsof -i -P -n | grep 6379`.

Being on Windows, I'd also advise restarting, just in case.

**Comment by amonsosanz** [comment]
I fixed a problem I had in my local environment and now I have all the containers running. Sorry about my [imprecise comment yesterday](https://github.com/0xPolygonID/issuer-node/issues/520#issuecomment-1808481742). I've not worked on this project lately. This is the complete list of containers you should have running:

```bash
$ docker ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS                  PORTS                    NAMES
8fcb6b0c93ee   issuer-api-ui              "sh -c 'sleep 4s && …"   9 minutes ago   Up 9 minutes            0.0.0.0:3002->3002/tcp   issuer-api-ui-1
29931c841d67   issuer-ui                  "/bin/sh /app/script…"   9 minutes ago   Up 9 minutes            0.0.0.0:8088->80/tcp     issuer-ui-1
e6b0094a8985   issuer-pending_publisher   "sh -c 'sleep 4s && …"   9 minutes ago   Up 9 minutes                                     issuer-pending_publisher-1
2f16c5411050   issuer-notifications       "sh -c 'sleep 4s && …"   9 minutes ago   Up 9 minutes                                     issuer-notifications-1
9918e0538d6f   issuer-api                 "sh -c 'sleep 4s && …"   17 hours ago    Up 17 hours             0.0.0.0:3001->3001/tcp   issuer-api-1
a1fa0725ef7a   postgres:14-alpine         "docker-entrypoint.s…"   18 hours ago    Up 17 hours (healthy)   0.0.0.0:5432->5432/tcp   issuer-postgres-1
f01ea5f8991f   redis:6-alpine             "docker-entrypoint.s…"   18 hours ago    Up 15 hours (healthy)   0.0.0.0:6379->6379/tcp   issuer-redis-1
d9566fb4dfcc   vault:1.13.2               "docker-entrypoint.s…"   18 hours ago    Up 17 hours             0.0.0.0:8200->8200/tcp   issuer-vault-1
```

Now that we know that this project has 8 services, let's see what's wrong on your end. First, though, you should be able to make Redis run. Let's first focus on this and later we will make the rest work.

I hope all this is somehow helpful for you too @skywormfol. We hijacked your threat...

**Comment by Xiaod0ng** [comment]
Hi team, a similar problem here. I was able to start the docker service for the first time, the UI page can be opened without problem. However, if the docker service is stopped, what's the proper way to resume the services? If I start the docker service in docker directly, or use `make run`, `make run-ui` to start the service, issuer-ui image is always not started. 
![image](https://github.com/0xPolygonID/issuer-node/assets/46312135/50ecb271-b69c-4c48-b306-63fc1523fe21)
Inside the docker image, it has log: /bin/sh: can't open '/app/scripts/deploy.sh': No such file or directory

**Comment by amonsosanz** [comment]
Hi @Xiaod0ng. Thx for reporting this issue. I'm able to reproduce it.

Apparently, the entry point of the docker image, [the deploy script](https://github.com/0xPolygonID/issuer-node/blob/main/ui/Dockerfile#L15), gets removed by [the script itself](https://github.com/0xPolygonID/issuer-node/blob/main/ui/scripts/deploy.sh#L34), making the UI run only the first time.

While we investigate the issue, you can re-run the UI service after it has been stopped by removing the image. This should not imply a rebuild of the complete image thanks to docker layering:

`docker rm issuer-ui-1 && make restart-ui`

or for Mac

`docker rm issuer-ui-1 && make restart-ui-arm`

**Comment by Xiaod0ng** [comment]
@amonsosanz Thank you for your prompt reply! The command can resolve the issue but it does rebuild the ui. I will test more to see if it really works. Will keep you updated.
![image](https://github.com/0xPolygonID/issuer-node/assets/46312135/58606df2-60e5-43e6-bfd1-e08afa751b5f)
BTW, for the network issue mentioned in above thread, if I run `make run`, then `make run-ui`, it won't have the error. If I run `make run-ui` only, it will show the error. Didn't try many times, do don't guarantee it can be reproduced stablely.

**Comment by amonsosanz** [comment]
I believe it's normal that the UI image is not rebuilt unless there are other changes.

I've opened a PR fixing the issue you reported [here](https://github.com/0xPolygonID/issuer-node/pull/542).

> BTW, for the network issue mentioned in above thread, if I run `make run`, then `make run-ui`, it won't have the error. If I run `make run-ui` only, it will show the error. Didn't try many times, do don't guarantee it can be reproduced stablely.

The "Network error" happens when for some reason the service running the API consumed by the UI (`issuer-api-ui`) fails to boot. This can happen for several reasons.

In the case of @Raj6939, apparently, he has an issue booting the Redis cache and therefore several containers fail booting.
In the case of @skywormfol, we don't know yet the source of the issue. It might be related to the vault, the generation of the DID, or anything else.

**Comment by Xiaod0ng** [comment]
Hi @amonsosanz , to add something to this issue, all my images are running (8 in total) and it's normal when openning from my laptop where hosting Docker. But when openning with my mobile phone, it's showing network error. I also tried with localtunnel to setup the public URL, but same behavior
![new ducument](https://github.com/0xPolygonID/issuer-node/assets/46312135/7a960d8d-7f07-48a2-af03-dcd39cb35f37)

**Comment by amonsosanz** [comment]
Can you please show here the settings/commands you use to run both ngrok and localtunnel?

**Comment by Xiaod0ng** [comment]
@amonsosanz Here you go:

ngrok: `ngrok http --domain usefully-blessed-sunbird.ngrok-free.app 8088`,  `usefully-blessed-sunbird.ngrok-free.app` is the customized domain ngrok assigned to me.

localtunnel: `lt --port 8088`

**Comment by amonsosanz** [comment]
Ok, there is the issue, you need to make publicly accessible the API (port 3002) and optionally the UI, as you already do.

You can keep using ngrok for the UI (port 8088) and then use local tunnel for the API with `lt --port 3002`. Then you need to set the publicly accessible URL of the API in the `ISSUER_API_UI_SERVER_URL` of the file `.env-api` and restart the api-ui container.

If you wonder, the reason to use local tunnel and not ngrok for the API is that some users have experienced CORS issues with ngrok removing the header `Access-Control-Allow-Origin`.

**Comment by Xiaod0ng** [comment]
@amonsosanz Hi, it still has the same error when openning with mobile browser. I have followed your instructions, settings are as following. 
In `.env-api`:
`ISSUER_API_UI_SERVER_URL=https://tame-items-lay.loca.lt` while the value is what localtunnel returned.
In `.env-issuer`:
`ISSUER_SERVER_URL=https://usefully-blessed-sunbird.ngrok-free.app/` while the value is customized ngrok domain.
`api-ui-1` container is restarted after setting the values.

**Comment by amonsosanz** [comment]
Have you restarted the API container?

`docker restart issuer-api-ui-1`

**Comment by Xiaod0ng** [comment]
@amonsosanz  Yes, the container was restarted after setting the variables.

**Comment by amonsosanz** [comment]
Sorry, you're right, the UI env vars are calculated in the image. You need to run:

`make restart-ui`

**Comment by Xiaod0ng** [comment]
@amonsosanz  Hi, I don't think it's right. I got network error even on my local computer. The error message in console is: Failed to load resource: the server responded with a full-mirrors-crash.loca.lt/v1/schemas:1 status of 511. `full-mirrors-crash.loca.lt` is localtunnel public URL. 
![image](https://github.com/0xPolygonID/issuer-node/assets/46312135/13088f27-48df-4acd-a4c7-02924c660b84)
I'm not sure whether it's related to this error from localtunnel. 
![image](https://github.com/0xPolygonID/issuer-node/assets/46312135/35b746bc-6898-40db-943a-98dfb0d4a2d8)

Could you please let me know whether the following is correct? I will try to host the sites in Azure instead of ngrok or localtunnel.
`ISSUER_API_UI_SERVER_URL` with port 3002 should be public;
`ISSUER_SERVER_URL` with port 3001 should be public.
Anything missing?

**Comment by amonsosanz** [comment]
The setup you were attempting is pretty common for testing. Let's give it one more try before Azure.

You only need to open in the browser the URL that localtunnel gives you. An input text should appear to enter your IP
so it can be whitelisted. After doing so, it should work.

**Comment by Xiaod0ng** [comment]
@amonsosanz  Hi, If I open the URL from localtunnel, it's API UI, not the UI. If I open ngrok URL, it's using previous localtunnel URL instead of the new output from localtunnel command. The env file is updated to latest URL and UI restarted with `make restart-ui`. It seems so confusing to me. 
![image](https://github.com/0xPolygonID/issuer-node/assets/46312135/81da4ef4-6e8b-4716-9cc2-ed9b05572bc9)

I appreciate if we can have a remote session or use other method to troubleshoot this issue.

**Comment by amonsosanz** [comment]
I've recorded a quick video showing you how I set up this in my local environment.

https://drive.google.com/file/d/1oA5qtoQhREGaSHO3P_YOpj7PY-I7Bfac/view

**Comment by Xiaod0ng** [comment]
@amonsosanz Thank you for your time! I finally got what you mean. But I'm having another issue right now, I will give it a try after fixing that one. Thanks again!

**Comment by amonsosanz** [comment]
I did not test it but yep it should work the same. The issue you had initially is that the UI was pointing to localhost, which is only available in the computer. Now that the change has been applied and you're using local tunnel, after white-listing your IP, you should be able to use the UI from other devices.

Take into account though that our UIs are not yet very mobile friendly, we will be improving this with the time.

**Comment by Xiaod0ng** [comment]
@amonsosanz Hi, I'm able to get it work now. The trick is about whitelist my IP in localtunnel. Thank you!

**Comment by amonsosanz** [comment]
Awesome! Thank you for your patience!
