### ISSUE TITLE
make generate-issuer-did error

### ISSUE THREAD

**Issue by xdimension** [0xPolygonID/issuer-node#548]
Got this error when running the command make generate-issuer-did
Tried to set ISSUER_VAULT_USERPASS_AUTH_ENABLED=true still doesn't work.

2023/11/18 04:00:58 INFO starting issuer node... revision=""
2023/11/18 04:00:58 INFO missing toml config file. Fallback to env vars err="Config File \"config\" Not Found in \"[/service /home/runner/work/sh-id-platform/sh-id-platform]\""
2023/11/18 04:00:58 INFO ISSUER_API_UI_ISSUER_DID value is missing
time=2023-11-18T04:00:58.728Z level=INFO msg="Vault userpass auth not enabled"
time=2023-11-18T04:01:02.806Z level=ERROR msg="creating identity" err="can't create babyJubJub key: Error making API request.\n\nURL: PUT http://vault:8200/v1/iden3/new/random/BJJ:07edebdbe78ddcc45c906318b1a6120b\nCode: 503. Errors:\n\n* Vault is sealed" id=<nil>
time=2023-11-18T04:01:02.806Z level=ERROR msg="error creating identifier" !BADKEY="cannot create identity: can't create babyJubJub key: Error making API request.\n\nURL: PUT http://vault:8200/v1/iden3/new/random/BJJ:07edebdbe78ddcc45c906318b1a6120b\nCode: 503. Errors:\n\n* Vault is sealed"

**Comment by martinsaporiti** [comment]
Hi @xdimension, if you want to configure the issuer node to authenticate against Vault with the userpass approach you must add these vars to .env-issuer file:

```
ISSUER_VAULT_USERPASS_AUTH_ENABLED=true
ISSUER_VAULT_USERPASS_AUTH_PASSWORD=issuernodepwd
```

Another approach is by using the vault root token. For that change first the .env-issuer like this:
```
ISSUER_VAULT_USERPASS_AUTH_ENABLED=false
ISSUER_VAULT_USERPASS_AUTH_PASSWORD=issuernodepwd
```
then run `make add-vault-token` to add the vault token to the .env-issuer file.
After running that command you should see something like this in that file:
```
ISSUER_KEY_STORE_TOKEN=hvs.XXX
````
Also, you can check the vault token running `make print-vault-token` and the result should be the same, hvs.XXX in this example.

**Comment by xdimension** [comment]
Thanks for your reply.
I tried again and when I run the command `make private_key=XXX add-private-key;` I got an error:

docker exec issuer-vault-1 \
vault write iden3/import/pbkey key_type=ethereum private_key=XXX
Error writing data to iden3/import/pbkey: Error making API request.

URL: PUT http://0.0.0.0:8200/v1/iden3/import/pbkey
Code: 503. Errors:

* Vault is sealed
make: *** [Makefile:147: add-private-key] Error 2

**Comment by martinsaporiti** [comment]
@xdimension can you paste here the vault container logs ?

**Comment by xdimension** [comment]
Hi @martinsaporiti 
I just git clone again this repo and it works now. I check that it has difference main branch commit than I cloned yesterday. So it seems it has been fixed.
Thanks.

**Comment by martinsaporiti** [comment]
Hi @xdimension, glad to heard that.

**Comment by neerajchowdary889** [comment]
still I'm getting issue on running make generate-issuer-did

**--logs:** 
WARN[0010] Found orphan containers ([issuer-vault-1 issuer-postgres-1 issuer-redis-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 1/1
 ✔ Container issuer-initializer-1  Started                                                                                                                                                                                               0.8s 
sleep 5
docker logs issuer-initializer-1
2023/11/23 16:42:43 INFO missing toml config file. Fallback to env vars err="Config File \"config\" Not Found in \"[/service /home/runner/work/sh-id-platform/sh-id-platform]\""
time=2023-11-23T16:42:43.073Z level=DEBUG msg=database url="postgres://polygonid:polygonid@postgres:5432/platformid?sslmode=disable"
2023/11/23 16:42:43 OK   20230103082420_initial.sql (244.4ms)
2023/11/23 16:42:43 OK   20230207173556_remove_unneded_field_from_identity_sql.sql (6.8ms)
2023/11/23 16:42:43 OK   20230303114429_add_schemas_table.sql (35.85ms)
2023/11/23 16:42:43 OK   20230308093840_add_connections_table.sql (31.91ms)
2023/11/23 16:42:43 OK   20230309164801_update_claims_mtp_proof_column.sql (6.45ms)
2023/11/23 16:42:43 OK   20230320144410_update_claims_mtp_column.sql (7.55ms)
2023/11/23 16:42:43 OK   20230322114550_add_links_table.sql (37.67ms)
2023/11/23 16:42:43 OK   20230329153017_add_column_issued_to_links_table.sql (6.28ms)
2023/11/23 16:42:43 OK   20230508112523_add_column_created_at_to_claims_table.sql (7.2ms)
2023/11/23 16:42:43 OK   202303311203222_add_pk_to_connections_table.sql (14.72ms)
2023/11/23 16:42:43 OK   202304121507181_add_linid_to_claims_table.sql (11.05ms)
2023/11/23 16:42:43 OK   202305111652000_remove_schema_attributes.sql (10.46ms)
2023/11/23 16:42:43 OK   202307051116210_add_schemas_version_title_description_column.sql (19.7ms)
2023/11/23 16:42:43 OK   202307111216560_update_schemas_version_title_column.sql (6.98ms)
2023/11/23 16:42:43 OK   202310090829241_update_identities_table.sql (6.02ms)
2023/11/23 16:42:43 OK   202311080942897_add_schema_type_description_to_claims.sql (5.35ms)
2023/11/23 16:42:43 goose: successfully migrated database to version: 202311080942897
time=2023-11-23T16:42:43.593Z level=INFO msg="migration done!"
2023/11/23 16:42:43 INFO starting issuer node... revision=""
2023/11/23 16:42:43 INFO missing toml config file. Fallback to env vars err="Config File \"config\" Not Found in \"[/service /home/runner/work/sh-id-platform/sh-id-platform]\""
time=2023-11-23T16:42:43.898Z level=INFO msg="Vault userpass auth not enabled"
time=2023-11-23T16:42:46.321Z level=INFO msg="publishing state to RHS" publishers=1
time=2023-11-23T16:42:46.321Z level=INFO msg="new state nodes" nodes="[{Hash:56762587... Children:[14711769... 0 0]}]"
time=2023-11-23T16:42:47.072Z level=ERROR msg="publishing state to RHS" err="no contract code at given address"
time=2023-11-23T16:42:47.073Z level=ERROR msg="creating identity" err="no contract code at given address" id=<nil>
time=2023-11-23T16:42:47.074Z level=ERROR msg="error creating identifier" !BADKEY="cannot create identity: no contract code at given address"

sed '/ISSUER_API_UI_ISSUER_DID/d' .env-api > .env-api.tmp
mv .env-api.tmp .env-api
docker stop issuer-initializer-1
issuer-initializer-1
docker rm issuer-initializer-1
issuer-initializer-1
