### ISSUE TITLE
Need Help with Create Claim

### ISSUE THREAD

**Issue by utkarsh-1905** [0xPolygonID/issuer-node#569]
#### Expected behaviour
Create a verifiable credential

#### Actual behaviour
![image](https://github.com/0xPolygonID/issuer-node/assets/83540694/4c498dfa-4b74-43cf-9ee2-643faf3c5ab7)
giving parse claim error

#### Steps to reproduce the problem
JSON Schema = https://raw.githubusercontent.com/utkarsh-1905/polygon-id-schemas/main/TitleSchema.json
Request Body = 
![image](https://github.com/0xPolygonID/issuer-node/assets/83540694/7eafd8a6-2ac0-46a9-aac4-4fbee9093a1f)

### System information

Issuer node version: `v2.3.3`
OS & Version: `Linux`
Browser & Version: `Chrome/Firefox/Safari/Edge`

#### Logs (if needed)
````
time=2023-12-02T18:31:41.582Z level=ERROR msg="error parsing claim" err="multiple parents found"
time=2023-12-02T18:31:41.582Z level=ERROR msg="credential subject attributes don't match the provided schema" err="error parsing claim"
time=2023-12-02T18:31:41.582Z level=ERROR msg="error parsing claim" err="error parsing claim"
time=2023-12-02T18:31:41.583Z level=INFO msg="http req" req-id=36404dbebaa1/XbJnNvSq2h-000311 method=POST uri=/v1/did:polygonid:polygon:mumbai:2qMSRWgNnnhmWdVB2MtLvp58H5P2J9pP6SBVsQXyX4/claims status=400 bytes=33 ua=PostmanRuntime/7.35.0 d=194.043249ms
````

When submitting logs, please submit them as text and not as screenshots.

**Comment by martinsaporiti** [comment]
Hi @utkarsh-1905 I've tested your schema and it worked as expected. My body request:
```
{
  "credentialSchema":"https://raw.githubusercontent.com/utkarsh-1905/polygon-id-schemas/main/TitleSchema.json",
    "type": "TitleCredential",
    "credentialSubject": {
        "id": "did:polygonid:polygon:mumbai:2qEATqfECVbCBzq9EhJpPSiv1xtJRpbMBKDaNM68Ci",
        "name": "Random User",
        "vin": "asdasd",
        "billCID" : "123456"
    },
  "expiration": 1773133352
}
```
please try your example in this environment: **https://self-hosted-platform.polygonid.me/** and try to update your issuer node code.

**Comment by slandymani** [comment]
Hi @utkarsh-1905, did you use did of issuer as id? I had the same error and the problem was that I was using issuer did as id, when I changed it to another one did the problem has gone.
