### ISSUE TITLE
Error while running the platform UI in standalone mode

### ISSUE THREAD

**Issue by hopinstein** [0xPolygonID/issuer-node#583]
I have been trying to run the issuer node in standalone mode and getting this error 

```time=2023-12-17T23:27:05.371Z level=ERROR msg="error getting identity by DID" err="no rows in result set" did=did:polygonid:polygon:main:2qAkTgqobSYrLXQxj1J3cfe

time=2023-12-17T23:27:05.371Z level=ERROR msg="issuer DID must exist" did="{Method:polygonid ID:polygon:main:2qAkTEp1r3cfe IDStrings:[polygon main 2qAkTgqobS8c5zu1J3cfe] Params:[] Path: PathSegments:[] Query: Fragment:}"

P.S: no worries I have removed parts from the DID.

**Comment by amonsosanz** [comment]
Hi, I assume you're following [this guide](https://devs.polygonid.com/docs/issuer/setup-issuer-ui/#standalone-mode-guide).

What is the output of the command `make generate-issuer-did`?

**Comment by hopinstein** [comment]
Hi @amonsosanz thanks for the quick response. the issue was me using a wrong pre-generated  DID 

a follow up question to this, For my use case I just need the credential related APIs and import schema which to my understanding doesn't need vault , Redis and Postgres for it's operation I wondering how I can achieve this because cost for these service is not something I want to incur upon

thank you!

**Comment by amonsosanz** [comment]
Redis and Postgres are essential components, while the necessity of Vault is more flexible. Here's a breakdown:

* **Vault**: It is crucial for storing the private key used to sign credentials, including the MetaMask private key required for publishing states. However, you have the option to implement an interface for storing these keys in a location of your choice, such as a file.
* **Redis**: This component is necessary for caching purposes.
* **Postgres**: Essential for storing all credentials, schemas, connections, etc., making it a necessary part of the setup.

Considering costs, you can potentially minimize them by running Vault and Redis using Docker Compose, which is a cost-effective solution. If you choose cloud deployment, costs may stem from the underlying infrastructure, such as EC2 instances.

Feel free to reach out for further clarification or if you have additional questions.

**Comment by hopinstein** [comment]
Hey @amonsosanz I'm sorry to keep you hanging, I did manage to run the node smoothly. Eventually had to run local instances of Redis and vault for staging. 

Closing the issue for now!

**Comment by amonsosanz** [comment]
Great to hear that! I'm really glad I could assist you in resolving the issue. If you have any more questions or need further assistance in the future, feel free to reach out. Take care!

**Comment by hopinstein** [comment]
thanks! @amonsosanz
