### ISSUE TITLE
Issue with Credentials status types.

### ISSUE THREAD

**Issue by revanth-sai24** [0xPolygonID/issuer-node#630]
#### Expected behaviour
should get the credentials status types of a VC as both.   
-Iden3ReverseSparseMerkelTreeProof
-SparseMerkelTreeProof

#### Actual behaviour
getting only SparseMerkelTreeProof

### System information

Issuer node version: `vX.X.X`
OS & Version: `Windows/Linux/OSX`
Browser & Version: `Chrome/Firefox/Safari/Edge`

#### Logs (if needed)

````
[logs]
````

When submitting logs, please submit them as text and not as screenshots.

**Comment by amonsosanz** [comment]
Hi, one reason for the `Iden3ReverseSparseMerkleTreeProof` to be missing in the credential is the issuer node configuration.

I assume that you're not using our demo issuer node to issue the credentials right?

If you're using your issuer node, take into account that the env var `ISSUER_CREDENTIAL_STATUS_RHS_MODE` must be set to `OffChain` for the credentials to get the `Iden3ReverseSparseMerkleTreeProof`.

You can find more details about all this [in the docs](https://devs.polygonid.com/docs/issuer/issuer-configuration/#rhs-off-chain).
