### ISSUE TITLE
Unable to publish state when revoke an MTP kind of VC

### ISSUE THREAD

**Issue by ly574605863** [0xPolygonID/issuer-node#643]
#### Expected behaviour
After revoke the MTP kind of VC, need do publish state

#### Actual behaviour
but it show there is no MTP kind of claim to publish

#### Steps to reproduce the problem
1. issue credential with MTP type
2. click publish state 
3. after published do revoke for the vc created
4. click publish state, and it shows "Request failed with status code 400: no MTP claims found to **process"**

### System information

Issuer node version: `v1.4.2`
OS & Version: `Windows/Linux/OSX`
Browser & Version: `Chrome/Firefox/Safari/Edge`

#### Logs (if needed)
This is because of when we try to publish state after do revocation, it query the claims with revoked is true and identity state is null, but if there is MTP VC, the identity state is not null after it was published to blockchain.

When submitting logs, please submit them as text and not as screenshots.

**Comment by javip97** [comment]
Hey @ly574605863, thanks for reporting. We're currently fixing it in this PR: https://github.com/0xPolygonID/issuer-node/pull/644.
