### ISSUE TITLE
Error while generating the did of the issuer node.

### ISSUE THREAD

**Issue by varshney565** [0xPolygonID/issuer-node#658]
#### Expected behaviour
when i am running the command make generate-issuer-did
it should generate the did of the issuer node.

#### Actual behaviour
but i am getting the error that saying wrong did metadata

### System information
these are my env settings
ISSUER_API_IDENTITY_METHOD=polygonid
ISSUER_API_IDENTITY_BLOCKCHAIN=polygon
ISSUER_API_IDENTITY_NETWORK=amoy
ISSUER_API_UI_KEY_TYPE=BJJ

Issuer node version: `main`
OS & Version: `Linux`
Browser & Version: `Chrome`

#### Logs 
````
[logs]
time=2024-04-24T09:49:25.998Z level=ERROR msg="adding genesis claims to tree" err="wrong DID Metadata"
time=2024-04-24T09:49:25.998Z level=ERROR msg="creating identity" err="can't add genesis claims to tree: wrong DID Metadata" id=<nil>
time=2024-04-24T09:49:25.998Z level=ERROR msg="error creating identifier" !BADKEY="cannot create identity: can't add genesis claims to tree: wrong DID Metadata"
````

When submitting logs, please submit them as text and not as screenshots.

**Comment by martinsaporiti** [comment]
Hi @varshney565, please try removing all the previous docker images and docker containers related to the issuer node (API, api-ui, pending-publisher and notifications). You can keep the containers related to infrastructure (postgres, redis, vault).

**Comment by varshney565** [comment]
yes i have removed all the previous docker images and the docker containers but still i got that issue.

**Comment by martinsaporiti** [comment]
That log error is because you are executing old code (not supporting amoy). In some way, docker is caching something if you have deleted previous images. Maybe you can try `docker builder prune`

**Comment by varshney565** [comment]
I have did as you said but it is not working.
I am currently using the main version.

**Comment by martinsaporiti** [comment]
main brach works with Amoy network.
