### ISSUE TITLE
Getting Errors while publishing did on chain using ethereum network and sepolia chain.

### ISSUE THREAD

**Issue by varshney565** [0xPolygonID/issuer-node#659]
#### WHAT I HAVE DONE
I have filled the env file with suitable parameters including setting the Ethereum node URL,Ethereum contract address,
ISSUER_API_IDENTITY_METHOD=polygonid,ISSUER_API_IDENTITY_BLOCKCHAIN=eth,ISSUER_API_IDENTITY_NETWORK=sepolia(as I am using sepolia network) ISSUER_API_UI_KEY_TYPE=ETH.
after that i have run the rhs service locally as mentioned in the polygonid docs about rhs.
after that I have done make up and set up the vault and generate the issuer_did and does make run.

#### ISSUE THAT I AM FACING
I am getting the below error while publishing the id to on chain and generating the claim,
PUBLISHING DID ON CHAIN
![p1](https://github.com/0xPolygonID/issuer-node/assets/87566789/6da06cb2-a25a-4cc0-b482-a2a8b2ed3538)
GENERATING THE CLAIM,
![p2](https://github.com/0xPolygonID/issuer-node/assets/87566789/53e772f9-7e9f-47e2-ba7a-0fe664e14ad4)
WHAT IT IS SHOWING ON ALCHEMY ABOUT PUBLISHING DID ON CHAIN.
![a1](https://github.com/0xPolygonID/issuer-node/assets/87566789/6cc2c1d3-708d-4b9b-adc0-2a597dd1c6e9)

**Comment by DSHIVAAY-23** [comment]
yes i am getting exactly the same issue  @martinsaporiti

**Comment by martinsaporiti** [comment]
Hi, ISSUER_API_IDENTITY METHOD, ISSUER_API_IDENTITY BLOCKCHAIN, ISSUER_API_IDENTITY_NETWORK variables are not used when you run the core API (running on port 3001). The command `make run` runs the core API.
So if you are running the core API and you want to use ETH identity you have to:
* Create an identity like this (example for amoy network):
```
# endpoint: HTTP://localhost:3001/v1/identities
# body:
{
    "didMetadata":{
        "method": "polygonid",
        "blockchain":"polygon",
        "network": "amoy",
        "type": "ETH"
    }
}
```
as result fo this you should have:
```
{
    "address": "c2092ca2b69d332501f44ffc26394dad1ec7af6a",
    "identifier": "did:polygonid:polygon:amoy:2qQ68JkRcf3ykwsHqB46fRPpdV9P1abkCjaHCEhSYF",
    "state": {
        "createdAt": "2024-04-26T11:31:10.546607Z",
        "modifiedAt": "2024-04-26T11:31:10.546607Z",
        "state": "0000000000000000000000000000000000000000000000000000000000000000",
        "status": "confirmed"
    }
}
```
* Send funds to the address **c2092ca2b69d332501f44ffc26394dad1ec7af6a**
* Publish the state
* Create a credential using did:polygonid:polygon:amoy:2qQ68JkRcf3ykwsHqB46fRPpdV9P1abkCjaHCEhSYF
Sample:
```
http://localhost:3001/v1/did:polygonid:polygon:amoy:2qQ68JkRcf3ykwsHqB46fRPpdV9P1abkCjaHCEhSYF/claims

{
    "credentialSchema":"https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json/KYCAgeCredential-v3.json",
    "type": "KYCAgeCredential",
    "credentialSubject": {
        "id": "did:polygonid:polygon:amoy:2qRsnkYbUHM3Cwx3WAowTjyUmH65zhhLmj88uGAfMM",
        "birthday": 19960424,
        "documentType": 2
    },
    "expiration": 202511092354
}
```
If you want to use the sepolia network you must have published the **State Contract** on that network.

**Comment by martinsaporiti** [comment]
Yeap,  it seems to be right. Have you changed the ISSUER_ETHEREUM_CONTRACT_ADDRESS with your state contract in Sepolia?

**Comment by ilya-korotya** [comment]
@varshney565 thank you for the issue. Wait for this [PR](https://github.com/iden3/contracts/pull/236) to be added to the main branch, or add this line and deploy the state contract again. It should help.

**Comment by saiharish-1029** [comment]
i am also facing the same issue.

**Comment by varshney565** [comment]
> Yeap, it seems to be right. Have you changed the ISSUER_ETHEREUM_CONTRACT_ADDRESS with your state contract in Sepolia?

yes i have changed that address

**Comment by ilya-korotya** [comment]
Hi @varshney565 @saiharish-1029 @DSHIVAAY-23. Could you please try redeploying the contract again? But first of all, pull the latest changes for the contract repository.

**Comment by DSHIVAAY-23** [comment]
Hi @ilya-korotya  yes we have redeployed the state contract and its working fine now we are not getting that error ,
Thankyou for support

**Comment by ilya-korotya** [comment]
@varshney565 @saiharish-1029 @DSHIVAAY-23. I'm going to close the issue because it's resolved. Feel free to open it again.
