### ISSUE TITLE
Getting error while generating the claim.

### ISSUE THREAD

**Issue by varshney565** [0xPolygonID/issuer-node#660]
Getting the error 
`{
  "message": "loading document failed: Bad response status code: 504"
}`
while generating the claim using custom schema.
This is my URL `POST /v1/did:polygonid:eth:sepolia:2tc31D4LTaC3eoLuLJs4ZJDEtgaeiBKMMmuXFAVTPu/claims`
and the request body 
`{
  "credentialSchema": "https://ipfs.io/ipfs/QmYdogegYBo6mF4taxK55eU9UWArdN8iqFaxb8xKA2Q8Dx",
  "type": "IITDelhiStudentID",
  "credentialSubject": {
    "id": "did:polygonid:eth:sepolia:2tc31D4LTaC36YuBGCGvFWKuz1haPwGHVCgE4WwLVf",
    "Name": "Shivam Varshney",
    "ID_number": 123,
    "course_name": "rust dsa 2024"
  },
  "expiration": 1903357766
}`

and here is the screenshot
![claim](https://github.com/0xPolygonID/issuer-node/assets/87566789/892e29ac-0549-422d-a33c-306cd1d87660)

**Comment by varshney565** [comment]
@mmilenkovic

**Comment by martinsaporiti** [comment]
Hi @varshney565, it seems is something related to IPFS. I was able to create the claim correctly with the body you sent:
<img width="848" alt="Screenshot 2024-05-01 at 07 36 35" src="https://github.com/0xPolygonID/issuer-node/assets/9029219/9bb44dcf-e07e-4593-a4d2-64800bdd2f05">
