### ISSUE TITLE
Getting error while publishing the did on chain.

### ISSUE THREAD

**Issue by varshney565** [0xPolygonID/issuer-node#661]
Hi,
I am running one EVM chain other than the one mentioned in iden3-core-library.
I am also sharing the code by which I am adding the chain in iden3 library

`params := core.DIDMethodNetworkParams{
		Method:      core.DIDMethodPolygonID,
		Blockchain:  core.Blockchain("arbitrium"),
		Network:     core.NetworkID("test"),
		NetworkFlag: 0b0100_0001,
	}
	err := core.RegisterDIDMethodNetwork(params, core.WithChainID(421613))
	if err != nil {
		log.Info(ctx, "ERROR WHILE ADDING arbitrium CHAIN Stage Network !", err)
		return
	}`
	
	the error that i am getting is no contract code at given address.
	
![aaaaaaaaaa](https://github.com/0xPolygonID/issuer-node/assets/87566789/98b968ba-9093-40ee-8d27-a8a6a536dd1d)

**Comment by varshney565** [comment]
@martinsaporiti

**Comment by martinsaporiti** [comment]
Hi you must add arbitrium network to the deploy script before deploy state contract: https://github.com/iden3/contracts/blob/2b29b3ac0c51fc6225ff1b786abc1194acb353f3/helpers/ChainIdDefTypeMap.ts

**Comment by varshney565** [comment]
Yes I have done that I have set the value to 0x241.
and while adding the blockchain I have set the value of networkflag to 0b1000001

**Comment by ilya-korotya** [comment]
@varshney565 could you share the contract address that you deployed to arbitrium, please?
