### ISSUE TITLE
State transition ZK Proof invalid

### ISSUE THREAD

**Issue by roderik** [0xPolygonID/issuer-node#670]
#### Expected behaviour

I suddenly cannot publish state transitions

![CleanShot 2024-06-13 at 07 49 52@2x](https://github.com/0xPolygonID/issuer-node/assets/16780/9506ae43-e7a0-4d9c-96c9-2a38834bbdac)

#### Actual behaviour

```
time=2024-06-13T05:44:05.547Z level=ERROR msg="Error during publishing proof:" err="execution reverted: Zero-knowledge proof of state transition is not valid" did=did:polygonid:polygon:amoy:2qRamLNxWXTgPxM5ZSeNnrn2XtEx1evCkh76oCQJZa
time=2024-06-13T05:44:05.547Z level=ERROR msg="error retrying the publishing the state" err="execution reverted: Zero-knowledge proof of state transition is not valid"
```

#### Steps to reproduce the problem

I don't know, nor what i did to cause it. I did deleted and revoked and deleted without revoking before publishing?
I also do not know how to recover my issuer at this point.

**Comment by x1m3** [comment]
Hi, @roderik . Can you give some tips about your configuration? What branch and version are you running? What is the value for ISSUER_ETHEREUM_MAX_GAS_PRICE env var? We've seen similar issues in amoy fixed increasing the values here.
