### ISSUE TITLE
Problems following v3.0 README

### ISSUE THREAD

**Issue by barrybecker4** [0xPolygonID/issuer-node#838]
#### Expected behaviour

I should be able to follow the README in order to get the issuer node working locally.

#### Actual behaviour

I encountered errors.

#### Steps to reproduce the problem

Check out the develop or master branch locally and try to follow the steps in the README exactly.

### System information

Issuer node version: `v3.0.0`
OS & Version: `Linux` Ubuntu VM
Browser & Version: `Firefox`

---
I checked out the develop branch of the issuer-node and tried the new README instructions. I have some questions and ran into problems.

Its not clear what should be set for the zkevm networkURL in resolvers_settings.yaml. 
networkURL: <your-rpc-url>

Is this what was previously the values of ISSUER_ETHEREUM_URL in the .env-issuer file? For that I had my Alchemy URL - https://polygon-amoy.g.alchemy.com/v2/1*************

One thing that is really not clear from the instructions is that there are multiple places where <your-rpc-url> needs to be replaced in the file. I just did the first one and then wondered why it did not work. Do I need to replace all of them?

On step 5, where do I get the Ethereum private key to import? Is that the private key from my Metamask wallet? I thought we used Matic and not Ethereum.

After some struggle, all my docker nodes are now up and healthy, however, when I try to access https://localhost:8088 it looks like it has failed because other environment vars need to be set. There was nothing in the instructions about those env vars. Where should they be set and what should they be set to? I do not see any occurrences of them in any of the .env.* files.
![image](https://github.com/user-attachments/assets/5138ad60-b693-4970-93b9-132d905c3fdd)

I noticed that there is an undocumented ui/.env.sample file in the ui dir. Although there is nothing about it in the doc, maybe I need to copy it to .env. Are any modifications to it needed?  I copied it to .env, and restarted everything, but still get the same errors about missing env vars.

I had submitted some suggestions previously in https://github.com/0xPolygonID/issuer-node/pull/765 that I thought might make it easier for users, but most of the suggestions were not incorporated into the revised README.

**Comment by barrybecker4** [comment]
I updated the develop branch locally and went through the instructions again. I see the same error when I try to access the UI at localhost:8088. Could it be that the ui/.env file is not being read [here](https://github.com/0xPolygonID/issuer-node/pull/839#discussion_r1835391332)?

**Comment by barrybecker4** [comment]
I worked around the CORS problem using a combination of an nginx reverse proxy and ngrok tunnels. It would be great if the README had some tips about this, since its not at all obvious what needs to be done.

You can use the subdomain field to define each service as a path on the same domain by setting up routing in your application or a reverse proxy. However, ngrok itself does not natively support path-based routing within the same configuration file for multiple tunnels.

An alternative approach with the free domain would be to use a reverse proxy (e.g., Nginx) on your local server to handle the path routing and point a single ngrok tunnel to it. Here’s how:

Set up Nginx to route each path to the correct local port.
Point a single ngrok tunnel to Nginx instead of directly to each service.
Step 1: Configure Nginx
Here's a sample configuration for nginx.conf:

```
nginx
server {
    listen 8080;
    server_name localhost;

    location /issuernode/ {
        proxy_pass http://localhost:3001/;
    }

    location /issuerapi/ {
        proxy_pass http://localhost:3002/;
    }

    location /issuerui/ {
        proxy_pass http://localhost:8088/;
    }
}
```
This setup will route requests to:

/issuernode to localhost:3001
/issuerapi to localhost:3002
/issuerui to localhost:8088

Then config ngrok like this:
```
tunnels:
  issuernode:
    proto: http
    addr: 3001
    hostname: issuernode-innocent-musical-vervet.ngrok-free.app
  issuerapi:
    proto: http
    addr: 3002
    hostname: issuerapi-innocent-musical-vervet.ngrok-free.app
  issuerui:
    proto: http
    addr: 8088
    hostname: issuerui-innocent-musical-vervet.ngrok-free.app
```

**Comment by x1m3** [comment]
About the CORS issue, I guess it is related to ngrok asking for a manual click the first time you browse the url.
